### ISSUE TITLE
Update tutorial

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/organization#10]
Google Drive has updated the interface for how you share files. Our tutorial needs new screenshots and instructions in this section:

https://github.com/nih-cfde/organization/blob/master/CommunicationManagementHelp.md#sharing-files

**Comment by josesanchez1815** [comment]
I'll take it

**Comment by ACharbonneau** [comment]
Cool. When you take things, please also assign yourself (top right) 
![image](https://user-images.githubusercontent.com/1719360/80745724-b9aa0b80-8aee-11ea-9e47-e8fff435fe5c.png)

**Comment by ACharbonneau** [comment]
And, when you do the PR, please link it into this issue. that will make it automatically close the issue when the PR is competed. 
![image](https://user-images.githubusercontent.com/1719360/80745858-ee1dc780-8aee-11ea-9947-0c7bc97c9cc7.png)

Perhaps these couple tagging things should make it into the little github workflow @abhijna is working on. They're new features that not everyone notices, but I really like them :)

**Comment by josesanchez1815** [comment]
@ACharbonneau  I want to add some images the images repository. But it says uploads have been disabled. Could you help me here? 
![Uploads disabled](https://user-images.githubusercontent.com/62918474/80750229-8e1e2580-8adc-11ea-8a20-1fa6de4e0424.PNG)

**Comment by ACharbonneau** [comment]
updated your access

**Comment by ACharbonneau** [comment]
please leave issues open until the changes are merged. It will close automatically since you linked the pull request

**Comment by ACharbonneau** [comment]
also, if you don't assign someone to check your pull request, its likely no one will see it :)
