### ISSUE TITLE
Update org docs

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/organization#46]
This front page hasn't been updated in a bit, I need someone to check/update:

- the mailing lists
- the readme so that there are links to all the docs stored in this repo
- delete any docs that moved to Welcome and update the links in this readme to point there
- any other changes/updates to make this readme more user friendly

**Comment by jeremywalter** [comment]
I'm going to try and rewrite this to make sense because there are github and zenhub docs that don't have any reference in the readme... going to try and make them fit in program management

**Comment by jeremywalter** [comment]
First major overhaul pushed... I'm still working on the Welcome site and will close this when everything looks good
