### ISSUE TITLE
Ontology Working Group

### ISSUE THREAD

**Issue by josesanchez1815** [nih-cfde/organization#69]
Organizer: Michelle Giglio
Organization: CFDE-CC

Members (Based on Michelle's Invite List on Slack https://cfdeworkspace.slack.com/archives/C01GP14DLJX)

Will update based on attendance on the first meeting

Doodle Poll is sent out and will close the 26th of January

Owen White (CFDE-CC)
Arthur Brady (CFDE-CC)
Marisa Lim (CFDE-CC)
Jeffrey Grethe (SPARC)
Sherry Jenkins (LINCS)
Haluk Resat (NIH)
Jonathan Silverstein (HuBMAP)
Erika Kim (NIH)
Chris Kinsinger(NIH)
David Chen (Ex-RNA)
Amanda Charbonneau (CFDE-CC)
Mark Musen (HuBMAP)
Saranya Canchi (CFDE-CC)
Jeremy Yang(IDG)
Jessica Binder (IDG)
Steve Mathias (IDG)
Cristian Bologa(IDG)
Avi Ma'ayan (LINCS, IDG)

**Comment by jeremywalter** [comment]
https://docs.google.com/document/d/1VoHHBeWfol6XNJa3kzOnOFuTaIrcLYbqKYQcOnj1oh4/edit#heading=h.3ia46913z0oa

Meetings are bi-weekly on Wednesdays.

**Comment by josesanchez1815** [comment]
@jeremywalter  you can close this issue if you do not need this info any more.
